version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=master
    - POSTGRES_PASSWORD=master
    - POSTGRES_DB=test_db
    build:
      context: .
      dockerfile: ./Dockerfile.db

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
  app:
    build: .